PointerStar/Client/Pages/Index.razor, PointerStar/Client/Pages/Room.razor, PointerStar/Server/Program.cs
=> Adding landing page

PointerStar/Client/Pages/Index.razor, PointerStar/Client/Pages/Room.razor, PointerStar/Client/Program.cs, PointerStar/Client/ViewModels/RoomViewModel.cs
=> Passing in room id and name

PointerStar/Client/Pages/Room.razor, PointerStar/Server/Room/InMemoryRoomManager.cs, PointerStar/Shared/RoomState.cs, Tests/Directory.Build.props, Tests/PointerStar.Client.Tests/ViewModels/RoomViewModelTests.cs, Tests/PointerStar.Server.Tests/Room/InMemoryRoomManagerTests.cs
First user into the room gets set as a facilitator.
=> Adding roles

.editorconfig, PointerStar/Client/Pages/Room.razor, PointerStar/Client/Pages/Room.razor.css, PointerStar/Client/Program.cs, PointerStar/Client/ViewModels/RoomViewModel.cs, PointerStar/Server/Properties/launchSettings.json, PointerStar/Shared/RoomHubConnection.cs, PointerStar/Shared/RoomState.cs, Tests/PointerStar.Client.Tests/ViewModels/RoomViewModelTests.cs
Also implemented the show/hide of votes
Fixes #37
=> Adding in voting buttons

PointerStar/Client/Pages/Room.razor, PointerStar/Client/Pages/Room.razor.css, PointerStar/Client/ViewModels/RoomViewModel.cs
=> Allowing facilitator to preview votes

PointerStar/Client/Pages/Room.razor
=> Showing users in different groups

PointerStar/Client/Pages/Room.razor, PointerStar/Client/Pages/Room.razor.css
This puts them in a table showing the results
It also highlights are rows that are tied for the most.
Fixes #9
=> Display vote results 

PointerStar/Client/Pages/Room.razor
* If Name is null display a popup to ask user for name
=> #36 Ask User for Name

PointerStar/Client/wwwroot/index.html, PointerStar/Client/wwwroot/manifest.json
https://learn.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-7.0&tabs=visual-studio#cache-first-fetch-strategy
Fixes #53
=> Disable service worker cache

PointerStar/Client/Cookies/Cookie.cs, PointerStar/Client/Program.cs, PointerStar/Client/ViewModels/RoomViewModel.cs, Tests/PointerStar.Client.Tests/ViewModels/RoomViewModelTests.cs
Caches last used name in a cookie and allows the user to re-use it.
Fixes #45
=> Cache last name in cookie

PointerStar/Server/Room/InMemoryRoomManager.cs, Tests/PointerStar.Server.Tests/Room/RoomManagerTests.cs
=> Enabling auto show votes should trigger if all votes casts

PointerStar/Client/ViewModels/RoomViewModel.cs, Tests/PointerStar.Client.Tests/ViewModels/RoomViewModelTests.cs
=> Fixing issue of room state updating trigging more updates

PointerStar/Client/Pages/Room.razor
=> When previewing votes show ellipse

PointerStar/Client/PointerStar.Client.csproj, PointerStar/Client/Program.cs, PointerStar/Client/Shared/MainLayout.razor, PointerStar/Client/wwwroot/index.html, PointerStar/Client/wwwroot/service-worker.published.js
https://github.com/jsakamoto/Toolbelt.Blazor.PWA.Updater
=> Testing out PWAUpdater package

PointerStar/Client/Components/ComponentBase.cs, PointerStar/Client/Pages/Room.razor, PointerStar/Client/ViewModels/RoomViewModel.cs, Tests/PointerStar.Client.Tests/ViewModels/RoomViewModelTests.cs, Tests/PointerStar.Server.Tests/Room/RoomManagerTests.cs
=> Adding more unit tests

PointerStar/Client/Pages/Room.razor
=> Fixing button font

PointerStar/Shared/RoomState.cs, Tests/PointerStar.Server.Tests/Room/RoomManagerTests.cs
=> Set default room view to autoshowvotes = true

PointerStar/Client/Pages/Room.razor
=> Adding Votes

PointerStar/Client/Components/UserDialog.razor, PointerStar/Server/Room/InMemoryRoomManager.cs, PointerStar/Shared/RoomState.cs, Tests/PointerStar.Server.Tests/Room/RoomManagerTests.cs
=> Limiting length of user names

PointerStar/Server/Room/InMemoryRoomManager.cs, Tests/PointerStar.Server.Tests/Room/RoomManagerTests.cs
Limits vote values to ones that are in the list of vote options on the room.
=> Vote validation

.editorconfig, PointerStar.sln, PointerStar/Client/Pages/Room.razor, PointerStar/Server/Room/InMemoryRoomManager.cs, PointerStar/Shared/RoomOptions.cs, PointerStar/Shared/RoomState.cs, Tests/PointerStar.Server.Tests/Controllers/RoomControllerTests.cs, Tests/PointerStar.Server.Tests/Room/RoomManagerTests.cs
=> Adding spellcheck
